# Site settings
title: Treehouse Lab Bulgaria
email: valentin.mihov@gmail.com
url: https://treehouselabbg.github.io
description: "Treehouse Lab Bulgaria - A small co-working office space in Sofia"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Threehouse Lab Bulgaria

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/treehouselabbg
  - title: facebook
    url:
  - title: github
    url: https://github.com/TreehouseLabBG

# Build settings
markdown: kramdown
permalink: pretty
